--- #YAML:1.0
name:                IO-Extended
version:             0.16
abstract:            more print functions
license:             ~
author:              
    - A. U. Thor <a.u.thor@a.galaxy.far.far.away>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
